### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by JustinGOSSES** [morganjwilliams/pyrolite#19]
**Is your feature request related to a problem? 
Not related to a problem, just at an idea for visualization of geochem data in newer interactive way when many samples resent.

Please describe.**
Used Mars chem cam data in Houston data visualization meetup data jam a while back and ended up making a parallel sets visualization with interactive selection that I thought was interesting and different.

It might be a new feature to include for cases where you have a large number of samples, especially if along time, depth, or space.

**Describe the solution you'd like**
Examples are here: 
https://github.com/JustinGOSSES/datajam_Mars_MajorElements

**Describe alternatives you've considered**
My example case above is interactive but could be static as well I guess.

**Additional context**
screenshots are at link above.

**Relevant References**
Haven't seen it used before so may or may not be actually useful.

**Comment by morganjwilliams** [comment]
I do like these diagrams - it's a good way to quickly explore multivariate data. And nice job on the example repo!

I'll put together something using [pandas.plotting.parallel_coordinates](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.plotting.parallel_coordinates.html) (with a bit of customization to improve axes etc) and leverage the move towards linking in more pandas plotting backends to eventually incorporate more interactive vis. 

Would be interesting to see if a centred log ratio transform is useful for major element parallel coordinate plots too.

**Comment by morganjwilliams** [comment]
I've added a static implementation of this which will be worth experimenting with on develop. Accompanied by a minimal example here: https://pyrolite.readthedocs.io/en/develop/usage/eg/plotting/parallel.html .

**Comment by JustinGOSSES** [comment]
Oh, nice! 

I assume the static nature is due to dependency on using matplolib then?

**Comment by morganjwilliams** [comment]
In this case yes. Could easily build something for an interactive mode for use with e.g. Jupyter, but for now this means the API is consistent with everything else in pyrolite.plot. In the meantime I'll keep interactive plotting libraries on my radar - especially things like [hvplot](https://github.com/pyviz/hvplot) which could minimise API changes.

**Comment by JustinGOSSES** [comment]
This has been built statically so we can close this
