### ISSUE TITLE
Pandas-indexing depreciation related bug (v1.0)

### ISSUE THREAD

**Issue by morganjwilliams** [morganjwilliams/pyrolite#31]
Since the recent release of `pandas` v1.0, new installations and current tests using the 'latest' version of pandas will break `pyrolite` tests with:

> Passing list-likes to .loc or [] with any missing labels is no longer supported

This is related to the depreciation of indexing with missing labels. As such we should be able to update instances where this functionality is needed to use `df.reindex()`. 

Alternatively, we could restrict the required version of `pandas` to `<1.0`, but this isn't a longer term solution and would soon result in conflict with other packages.

**Comment by morganjwilliams** [comment]
The aspects which were causing current tests to fail has been addressed, but there remain a number of scenarios where this applies. Other scenarios where this is relevant will be patched (especially within `pyrolite.geochem.transform`), and new tests will be developed to address indexing with missing values.

**Comment by rbeucher** [comment]
Hi @morganjwilliams 
I have encountered that bug while reviewing the Jupyter notebook: REE_V_radii.

**Comment by morganjwilliams** [comment]
@rbeucher thanks for the heads up. I'll have a look at this shortly, Could you let me know if this for the master or develop version, and whether you are running this locally or via binder?

**Comment by rbeucher** [comment]
I am running it locally in a virtual python 3.8 environment.
I am working on the master branch as I assume this is the one to be reviewed for PyOpenSci.

My Pandas version is 1.0.3.

The `normalization` notebook fails for the same reason.

**Comment by rbeucher** [comment]
The `lambdas_dimreduction` notebook also fails. This is all related to the REE_V_radii function.

**Comment by morganjwilliams** [comment]
Thanks for the info. This is likely to come up a few times for the current master, so I can either put out another release or refer you to develop in the meantime.

**Comment by morganjwilliams** [comment]
Closing this one for now - the pandas indexing issues related to`REE_v_radii` and  `pyrolite.geochem` should now largely be addressed (including in v0.2.8), especially when using the `pyrolite.geochem.pyrochem` and `pyrolite.plot.pyroplot` interfaces which should now not try to select missing columns/reindex to handle missing columns (for pyrochem/pyroplot respectively).
