### ISSUE TITLE
Reference Compositions Database Page

### ISSUE THREAD

**Issue by morganjwilliams** [morganjwilliams/pyrolite#38]
**Is your feature request related to a problem? Please describe.**
The reference compositions available in `pyrolite` are listed at the bottom of the normalisation example, but are otherwise difficult to find.

**Describe the solution you'd like**
Ideally, the reference compositions would have a dedicated documentation page, including improved bibliographic info for these items so they're appropriately cited.

**Describe alternatives you've considered**
Such a page could be listed under `API`, but equally we could add a separate menu item for data/databases (`Databases` seems appropriate here). This would then serve as a place to mention all the `pyrolite` data items including the reference composition database, the mineral database, the timescale, Shannon radii and Aitchison data.

**Comment by kaarelmand** [comment]
I can certainly try to help with this issue, at least for the shale references.

**Comment by morganjwilliams** [comment]
@lavender22 - I'll leave this with you in the meantime. When the page is about ready to go maybe ping @kaarelmand for some shale info.

**Comment by morganjwilliams** [comment]
I've added a new branch to work on these pages ([docs-pyrolite.data](https://github.com/morganjwilliams/pyrolite/tree/feature/docs-pyrolite.data)), with a draft structure under `docs/data`.

**Comment by kaarelmand** [comment]
Just for safekeeping in case I disappear again, here's what I have currently written on the shale/mud reference compositions I added in PR #37 (largely based off of Bau et al., 2018):

```
Shale/mud reference compositions
================================

These reference compositions are mostly used to normalize geochemical data in sedimentary, aqueous, and environmental geochemistry, for example in studies of rare earth element (REE) cycling.
Shales are particularly popular reference compositions in these fields, since they represent a mixture of detrital sources that approach the average composition of the upper continental crust.
Therefore, they represent an idealized "detrital background," deviations from which act as indicators of various geochemical processes.
Given their nature, the provided shale composites are all quite similar, with only minor differences.
Most papers in the related fields employ PAAS_TM1985, but other options may be preferred, for example for public engagement purposes or when dealing with legacy data.

1) PAAS_TM1985 -- Post-Archean Australian Shale by Taylor and McLennan (1985), containing major and minor element data.
This is by far the most widely used shale reference composition for REE work.
Commonly cited as Taylor and McLennan (1985), the sample compilation is the original work of Nance and Taylor (1976); the REE vales were later mathematically smoothed by McLennan (1989).
Additional elements were reported in McLennan, 2001.
Bear in mind that Tm and Lu concentrations weren't actually measured, but instead mathematically inferred based on neighbouring elements.

2) PAAS_Pourmand2012 -- Post-Archean Australian Shale by Pourmand et al. (2012).
Only contains rare earth element + yttrium data.
This is a more modern and smoother version of PAAS, with the advantage that all REE have actually been measured, but it is not as widely used in literature.
Despite the name, this comes from a wholly different set of samples than the more famous PAAS_TM1985, though it produces a very similar REE pattern.

3) NASC_Gromet84 -- North American Shale Composite by Gromet et al. (1984), containing major and minor element data. The sample compilation contains 40 mainly North American, mainly Paleozoic shale samples for which Gromet et al. provided new major and REE compositions.
Taylor & McLennan (1985) and McLennan (2001) included some additional measured elements.
NASC is used extensively in older literature, but less so than PAAS; it serves a purpose today if normalization specifically to North American material is needed.
But keep in mind that only 20 of the samples in this composite are actually known to originate from North America.
The sample set was originally compiled by Haskin and Haskin (1966).

4) EUS_Bau2018 -- European Shale by Bau et al. (2018), containing only REE and yttrium.
The main purpose of Bau et al. in publishing this REE reference was to help alleviate non-expert fears about normalization of European REY data to that of shales from other continents.
As such, it might be useful for studies of REY studies specifically in the European context, especially if substantial public engagement is expected.
This sample set originates with Minami et al. (1935) and a previous set of REE analyses was reported by Haskin and Haskin (1966).

5) PHS_Condie1993 -- Phanerozoic Cratonic Shale by Condie (1993).
This compilation is similar to both PAAS or NASC.
Today, it is most useful in conjunction with PRS_Condie1993 and ARS_Condie1993 to compare and normalize samples from different eons to an evolving crust.

7) PRS_Condie1993 -- Proterozoic Cratonic Shale by Condie (1993).
May be useful in normalizing samples specifically from the Proterozoic.
Used in conjunction with PHS_Condie1993 and ARS_Condie1993.

8) ARS_Condie1993 -- Archaean Cratonic Shale by Condie (1993).
May be useful in normalizing samples specifically from the Archean.
Used in conjunction with PHS_Condie1993 and PRS_Condie1993.

9) MUQ_Kamber2005 -- Mud from Queensland by Kamber et al. (2005). This is a set of samples from unconsolidated, fine-grained sediments (i.e., not shale) which has gained some traction as an alternative proxy composition for the upper continental crust. Its middle REE concentrations are somewhat elevated when compared to the shale compositions.
```

**Comment by morganjwilliams** [comment]
Thanks @kaarelmand! Will keep you in the loop for this issue.

**Comment by morganjwilliams** [comment]
I've merged the feature branch for this back into develop after putting together a 'data gallery' similar to the other examples. I've also updated each of the reference compositions to include 'Citaiton', 'DOI' and 'Description' fields so we might be able to automate pulling in some of this information. To make this a bit easier for the next person who wants to pull in another composition I've also added an example template under pyrolite/data/geochem (refcomp_template.csv). This is now live on the development version of the docs: https://pyrolite.readthedocs.io/en/develop/data/index.html

**Comment by kaarelmand** [comment]
Great, thanks! Should I open a PR to add these descriptions to the refcomp files?

**Comment by morganjwilliams** [comment]
@kaarelmand if you'd like to, sure. Eventually I'll try and get the citations to interlink/reference the same citation.

**Comment by morganjwilliams** [comment]
[This page is now live on the master version of the docs](https://pyrolite.readthedocs.io/en/master/data/refcomp.html), but the interlinking between descriptions and citations is still something which needs to be worked out in more detail. One idea would be to generate a HTML table in the docs [conf.py](../blob/develop/docs/source/conf.py#L300) and add a mapping to a variable for the full and subsets of the table in the RST prolog (extending what's there in terms of descriptions for each of the available normalisations, as used on the [normalization example page](https://pyrolite.readthedocs.io/en/develop/examples/geochem/normalization.html).

**Comment by morganjwilliams** [comment]
With the addition of DOIs and citations added to the [refcomp page](https://pyrolite.readthedocs.io/en/develop/data/refcomp.html#composition-list), I think this one mostly satisfies the requirements here - we could add more descriptive content in future if it'd be useful.
