### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by ThirstyGeo** [morganjwilliams/pyrolite#47]
**Describe the bug**
ENCOMP impute example missing.

**To Reproduce**
1. Visit [documentation](https://pyrolite.readthedocs.io/_/downloads/en/master/pdf/)
2. Click example for [ENCOMP](https://pyrolite.readthedocs.io/_/downloads/en/master/examples/comp/EMCOMP.html )

**Comment by morganjwilliams** [comment]
Hey @ThirstyGeo, thanks for the bug report! Regarding EMCOMP, the example added back in v.0.1.4 (a page linked to on the changelog, but now missing from the gallery) was removed from the docs a while back - I want to write up some more tests and validate that this works as expected before encouraging folks to use this (as it was translated form MATLAB, which I haven't had that much to do with previously), but this isn't on the top of the todo list for the moment. If you are interested in EMCOMP [the API docs are still there](https://pyrolite.readthedocs.io/en/develop/api/comp/impute.html), and you're welcome to try it out and assess it yourself. For a little more info, see #6.

In the meantime I'll remove the dead link from the changelog, so as not to lead folks into a maze.
