### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gdma1977** [morganjwilliams/pyrolite#50]
**Describe the bug**
I have imported a panda array of REE + Y data. pyrolite only recognizes Gd and Tb as REEs in the dataframe when using df.head(5).pyrochem.REE, however, all are there in the order La, Ce...Lu, Y. It doesn't seem to make a difference if I add or remove an empty column for Pm. When I plot the spidergram only Gd and Tb are plotted. Any ideas?

[WV REE chondrite.xlsx](https://github.com/morganjwilliams/pyrolite/files/6055814/WV.REE.chondrite.xlsx)

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**
Expected all REEs to be identified and plotted

**Environment:**
 - OS: Windows 10 Home 64 10.0.19042 
 - Python Version 3.7.4
 - Pyrolite Version latest

**Additional Context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by morganjwilliams** [comment]
Hey @gdma1977, thanks for noting that you managed to sort this one out yourself over on Gitter. Looking at the file, it looks like there are some spaces in the column names, and I can get it to work locally after these are removed. In case anyone else finds an issue like this in the future, the following should sort you out:

```python
df = pd.read_excel(<PATH_TO_FILE>)
df.columns = [c.strip() for c in df.columns]

df.pyroplot.REE()
```
