### ISSUE TITLE
conda Packaging

### ISSUE THREAD

**Issue by morganjwilliams** [morganjwilliams/pyrolite#51]
While pyrolite has been on PyPI for a while, it'd be good to get a conda-forge recipe together to better support conda-based users.

For reference, there's a [guide on contributing packages](https://conda-forge.org/docs/maintainer/adding_pkgs.html) which might be a handy starting point. It looks like it should be relatively simple to set this up given it's already on PyPI.

**Comment by eazzzon** [comment]
Hi Morgan,

Creating a conda-forge recipe for pyrolite is quite simple as it's already on PyPI. I have created the recipe and would like to know how I could contribute to this part? From what I understand maybe it's better that the orginal maintainer not contributor open a PR in [conda-forge's page](https://github.com/conda-forge/staged-recipes)?

**Comment by morganjwilliams** [comment]
Hi @eazzzon! I'm happy to add the PR to conda-forge, and it looks like for any PyPI version updates it should automatically get updated there, which is handy. Given how the conda-forge system is set up it doesn't seem to make much sense to add it directly to the pyrolite repo, but you could add it as a code block here if that suits - otherwise I've created a fork of `staged-recipies` and will add a `morganjwilliams/staged-recipies/pyrolite` branch you could pull request to.

**Comment by eazzzon** [comment]
Hi, I added the recipe here, hope that works. and maybe you could add other contributors in the recipe maintainers?

[meta.yaml.zip](https://github.com/morganjwilliams/pyrolite/files/6383845/meta.yaml.zip)

**Comment by morganjwilliams** [comment]
Thanks @eazzzon! Will have a look at sorting it out tomorrow.

**Comment by morganjwilliams** [comment]
I've now added a PR to [`staged-recipies`](https://github.com/conda-forge/staged-recipes/pull/14748); @eazzzon if you could comment in that thread that you're also happy to be a maintainer that'd be great!

**Comment by eazzzon** [comment]
maybe try this one, I guess the issue raised with ```noarch python```, which pyrolite isn't pure python (```python >= 3.6```). I commented ```noarch python``` in the recipe. hope this works
[meta.yaml.zip](https://github.com/morganjwilliams/pyrolite/files/6407962/meta.yaml.zip)

**Comment by morganjwilliams** [comment]
Thanks @eazzzon, I'll give it a spin.

**Comment by morganjwilliams** [comment]
I've removed the explicit dependency for `pathlib` on `develop`, so with luck this should be possible _after_  this is merged during the release of 0.3.1; I've updated the tag to have this done by 0.3.2.

**Comment by morganjwilliams** [comment]
`pyrolite` is now on `conda-forge`, with the feedstock here: https://github.com/conda-forge/pyrolite-feedstock
