### ISSUE TITLE
CIPW Norm

### ISSUE THREAD

**Issue by morganjwilliams** [morganjwilliams/pyrolite#53]
pyrolite currently contains a stub for the CIPW Norm ([code](https://github.com/morganjwilliams/pyrolite/blob/master/pyrolite/mineral/normative.py#L141), [docs](https://pyrolite.readthedocs.io/en/master/api/mineral.html?highlight=CIPW#pyrolite.mineral.normative.CIPW_norm)) which should be soon filled out. This is currently being worked on, and should be out for v0.3.1.

I've created a feature branch for this under [`feature/CIPWNorm`](https://github.com/morganjwilliams/pyrolite/tree/feature/CIPWNorm), and pull requests should be directed there; this will then be successively merged into `develop` and eventually `main` once released.

### Progress

- [x] CIPW Norm implementation
- [ ] Unit tests for basic functionality and concurrency with existing methods
- [x] Docs example illustrating it's use
- [x] Merged into `develop`

**Comment by ChetanNathwani** [comment]
Hi @morganjwilliams and pyrolite team,

I have had a stab at this. This follows the Verma et al. (2003) CIPW norm, using only major elements for now. I have had a go at testing this - Verma has a software package called IgRoCs which calculates his norm. His software has a test dataset, which we can use to compare the outputs from IgRoCs and pyrolite. These tests show a good performance for most minerals asides from magnetite, nepheline and perovskite. I have spent some time debugging to get this far and now am struggling to pin down any errors I may have made. A fresh pair of eyes would be beneficial to help.

![CIPW_tests](https://user-images.githubusercontent.com/82047572/113893389-e1095e00-97be-11eb-8b34-4a8e06732ef8.png)

**Comment by morganjwilliams** [comment]
@ChetanNathwani looks good, will follow up shortly. Feel free to make a pull request onto the [CIPW norm branch](https://github.com/morganjwilliams/pyrolite/tree/feature/CIPWNorm) if you're happy to put a development version out there - otherwise I'll catch up with you via other channels.

**Comment by bomtuckle** [comment]
Hey @ChetanNathwani,

I have also been working on some code to calculate norms, also based on Verma. I got in touch with @morganjwilliams a while ago and he said you were working on it, but I continued my work as I wanted to get it done anyway. I can appreciate your struggles with squishing the bugs on this!

My code _seems_ to be working, though I haven't compared it to IgRoCs output as you have. I will try that before saying its working with 100% confidence!

I would be happy to look over your code to see if I can help you debug. I need to get to grips with git, but there may also be potential to merge our work? There are some things I know I am missing (for instance how I handle the Fe correction - not sure how you are doing this?), but on the other hand I have incorporated minor elements.

Let me know what you think. Im really keen to collaborate on this if you are happy to.

Cheers
Tom

**Comment by ChetanNathwani** [comment]
Hi @bomtuckle,

Awesome to hear it. Yes - a good idea to merge our efforts.

I am not able to post the code on here, I think it has to be a pull request but not sure if I am doing it correctly (I am new to Git). Perhaps we can organise a call to catch up on this with @morganjwilliams to define a plan of action? 

The Fe correction is being dealt with using the old school approach of Le Bas. We could perhaps add the Middlemost approach in eventually too. Great to hear you've dealt with trace elements, I had lost my patience by then.

Anyway, hopefully we can organise a call soon, let me know when works, Next week Weds-Fri I will be more free.

Cheers
Chetan

**Comment by morganjwilliams** [comment]
Hi @ChetanNathwani and @bomtuckle!

Just a quick note that the pull request isn't explicitly required (it's kind of nice from a development perspective and means your username will pop up as a contributor to the repository, but otherwise is a formality) and if it's a bit confusing we can just add code snippets here and go that way. Happy to catch up in the coming week or so, and I can go through this with you to give you an idea of what's involved.

@ChetanNathwani I had a look through your CIPW and have a few suggestions, but thus far I haven't found anything obviously buggy - overall looks pretty good! I think that your precision concerns are probably one of the contributing factors but I have a solution for that. When we catch up I might get the test data from you also to confirm/deny.

**Comment by bomtuckle** [comment]
Hey both,
Would be good to talk to both of you about about all this. Im a bit tied up next week, but could squeeze something on Monday morning from 10 (uk time) or Tuesday morning.

**Comment by bomtuckle** [comment]
> 
> 
> Anyway, hopefully we can organise a call soon, let me know when works, Next week Weds-Fri I will be more free.

Sorry, didnt read this properly. I might be able to do Friday morning if need be

**Comment by morganjwilliams** [comment]
@ChetanNathwani @bomtuckle - I'll connect with you both over email and sort out a time to catch up.

**Comment by morganjwilliams** [comment]
@ChetanNathwani @bomtuckle I've merged Chetan's norm into the pyrolite feature branch and pushed a few updates, including some simple unit tests which check that it runs on a dataframe and some of the logging output works. There are some variable name changes in dbe252b02436de9ad2b5c38abb14f5da2b7ad739 which are worth checking, and otherwise a little reorganisation here and there for readability and conciseness.

**Comment by morganjwilliams** [comment]
I think the Middlemost/Le Maitre Fe correction should be able to be done in a vectorised way so will see if I can do that today also.

**Comment by bomtuckle** [comment]
> 
> 
> I think the Middlemost/Le Maitre Fe correction should be able to be done in a vectorised way so will see if I can do that today also.

Hey @morganjwilliams.

Sorry ive been a bit busy over the past month and havnt been too active here. I have been working on code for my own project and have writtent my own Fe Correction function that is vectorised. I have put it on the norms feature branch if you want to look. I have seprated it out as there are some arguments that need to be specified and maybe it could get a bit long winded if they are in the norms function?

I think the correction method we are using is from Le Maitre (1976) not Middlemost. There are also two different adjustments that you can make based on the igenous type (volcanic/plutonic). I think the middlemost correction uses the TAS clasification to then apply a certain correction factor. This could be easily done using the pyrolite classification function.... I think?

**Comment by morganjwilliams** [comment]
@bomtuckle no worries, I suspect it's similarly busy for everyone this time of year! I'll take a look at the Fe correction and if it fits perhaps ask you to pull it across.

As for the TAS-based corrections, that should be easy enough to do with the pyrolite TAS classifier; I haven't looked at this yet but once I've finished the once-over looking for potential bugs in the current CIPW Norm I'll get onto that.

**Comment by morganjwilliams** [comment]
@ChetanNathwani I've been able to verify a few things here, but like your original calculations I get a bit of a mess comparing Verma's results to mine on the output end. The 'adjusted' values in the Verma test data correspond nicely to the adjusted Wt% compositions before the norm, so at least the prep and iron correction work as expected there.

I've fixed a few errors here and there (mainly introduced by me in converting some things across and changing the iron correction); for a number of minerals the norm we calculate here is pretty similar, but there are few which are consistently bad still (Or+/-Ab, Di, Neph, olivine seems to be offset, we're not currently seeing the leucite and perovskite where we should).

**Comment by ChetanNathwani** [comment]
> @ChetanNathwani I've been able to verify a few things here, but like your original calculations I get a bit of a mess comparing Verma's results to mine on the output end. The 'adjusted' values in the Verma test data correspond nicely to the adjusted Wt% compositions before the norm, so at least the prep and iron correction work as expected there.
> 
> I've fixed a few errors here and there (mainly introduced by me in converting some things across and changing the iron correction); for a number of minerals the norm we calculate here is pretty similar, but there are few which are consistently bad still (Or+/-Ab, Di, Neph, olivine seems to be offset, we're not currently seeing the leucite and perovskite where we should).

@morganjwilliams Yes - so seems like we are having the same issues. Hmm... I wonder whether there could be something different that the IgRocs programme is working off - perhaps the method changed since the paper published or maybe there are errors we are unaware of... What do you think best to do next? I've spent many hours trying to debug and not sure what to do next (I assume you've already done the same).

**Comment by morganjwilliams** [comment]
Hi @ChetanNathwani! There certainly might be a few errors in the mix, or just differences we don't know about. I can spend a bit more time looking at it, but otherwise we can look to round off a few things and test what we can. I can leave a warning on the function until we're happy with it (e.g. for v0.3.1, aiming to clean things up for v0.3.2/the next version), but if we finish the core aspects and merge it across to `develop` we can give @bomtuckle a chance to merge in a few of the extra trace element steps too (this will involve a few extra changes rather than just a clean merge of new code).

**Comment by ChetanNathwani** [comment]
> Hi @ChetanNathwani! There certainly might be a few errors in the mix, or just differences we don't know about. I can spend a bit more time looking at it, but otherwise we can look to round off a few things and test what we can. I can leave a warning on the function until we're happy with it (e.g. for v0.3.1, aiming to clean things up for v0.3.2/the next version), but if we finish the core aspects and merge it across to `develop` we can give @bomtuckle a chance to merge in a few of the extra trace element steps too (this will involve a few extra changes rather than just a clean merge of new code).

Ok sounds good @morganjwilliams! It will be good to also see whether @bomtuckle's code is able to avoid any of the same issues that seem to be present in this code, or whether they seem to be unavoidable! Sorry have been bit busy recently, but do let me know where I can chip in.

**Comment by morganjwilliams** [comment]
Hey @ChetanNathwani, no worries, we're all a bit the same, and you've already put a lot of work into this one! I'll look to merge this across to `develop` after adding a warning to the function; from there I'll try and round of a few things around tests and maybe a docs example page (with a similar warning) before giving @bomtuckle a chance to make a PR and merge in some changes (if he has time to do so..).

**Comment by bomtuckle** [comment]
Hey @ChetanNathwani @morganjwilliams ,

I have got round to comparing my norms with the code currently in the pyrolite feature branch and I _think_ my results are showing a better fit to the output from IgRocs:

![image](https://user-images.githubusercontent.com/7592322/122758128-5948d100-d290-11eb-9559-8fcfb7206414.png)
![image](https://user-images.githubusercontent.com/7592322/122758192-6bc30a80-d290-11eb-875d-12493f75e118.png)
![image](https://user-images.githubusercontent.com/7592322/122758236-77163600-d290-11eb-8ed2-6c7f40988dd5.png)
![image](https://user-images.githubusercontent.com/7592322/122758283-85645200-d290-11eb-862f-c53f64e7fd85.png)
![image](https://user-images.githubusercontent.com/7592322/122758311-8f865080-d290-11eb-90b1-4bbadb0d3132.png)
![image](https://user-images.githubusercontent.com/7592322/122758341-9745f500-d290-11eb-8e35-7d5856e46498.png)
![image](https://user-images.githubusercontent.com/7592322/122758369-a036c680-d290-11eb-82e9-b1c50376238b.png)
![image](https://user-images.githubusercontent.com/7592322/122758400-a9c02e80-d290-11eb-81f1-72aa8b65cea9.png)

**Comment by morganjwilliams** [comment]
Hey @bomtuckle and @ChetanNathwani - just a heads up that I've merged the CIPW branch into develop. I won't have time to round this off this week (a few things to finish for Goldschmidt...), but will look at it again next week.

@bomtuckle - it looks like you have things fairly close there, feel free to add a pull request to `develop` if you'd like to integrate some/all of it and I'll take a look when I get a spare hour.

**Comment by morganjwilliams** [comment]
Thanks! I'll do a bit more digging and see what I can figure out, I'll also add the free components to the return value somewhere. I'll look to see if there's any blatant correlation or commonality for the compositions with magnetite norms which lie off the trend.

**Comment by morganjwilliams** [comment]
In our test dataset, there's only a few analyses with F present - and I suspect each of the two groups of analyses have different units (one ppm, one wt% - the same issue for Cl also, I think both should be ppm). Regardless it seems that in both cases there is no normative fluorite calculated, which seems a bit strange. I wonder if it could be due to the inclusion of string values (`'n.a.') in this column? @ChetanNathwani - any thoughts?

As for magnetite, the strongest correlations are with silica deficit/nepheline, but these don't explain the link directly as magnetite is calculated well before these are considered. Instead there's likely something going on with the iron calculations, as compositions with normative hematite represent the bulk of those with offsets in the normative magnetite (not quite 1:1, but these are on similar scales of magnitude).

**Comment by ChetanNathwani** [comment]
> In our test dataset, there's only a few analyses with F present - and I suspect each of the two groups of analyses have different units (one ppm, one wt% - the same issue for Cl also, I think both should be ppm). Regardless it seems that in both cases there is no normative fluorite calculated, which seems a bit strange. I wonder if it could be due to the inclusion of string values (`'n.a.') in this column? @ChetanNathwani - any thoughts?
> 
> As for magnetite, the strongest correlations are with silica deficit/nepheline, but these don't explain the link directly as magnetite is calculated well before these are considered. Instead there's likely something going on with the iron calculations, as compositions with normative hematite represent the bulk of those with offsets in the normative magnetite (not quite 1:1, but these are on similar scales of magnitude).

Sorry just catching up. I am a little out the loop but I am not sure for F. I agree it looks like there's two different units present. I wondered if maybe the F and Cl are being used for apatite but I imagine this isn't always the case? I agree that magnetite is likely related to an Fe conversion issue.

**Comment by morganjwilliams** [comment]
Thanks @ChetanNathwani - I might look to modify the test dataset and make sure all of F and Cl data are in ppm as per Verma's paper, if that sounds reasonable? For the Fe-conversion issue, perhaps we can debug this further after merging. Speaking of merging - I have a draft docs page which shows some aspects of the CIPW Norm but will get your input into what you'd like to see there after it's merged into develop and built on the docs page. There are also some basic tests there to make sure that no errors are being thrown, but it'd be good to have a few more specific test cases to make sure we capture a few edge case scenarios or unexpected inputs etc.

**Comment by morganjwilliams** [comment]
I've updated the units for those specific elements and removed the `n.a.` null/missing values. If you get a chance to re-run this and check the SINCLAS output let me know and we can re-integrate that output to see how it'll affect the comparison.

**Comment by ChetanNathwani** [comment]
> I've updated the units for those specific elements and removed the `n.a.` null/missing values. If you get a chance to re-run this and check the SINCLAS output let me know and we can re-integrate that output to see how it'll affect the comparison.

Hi Morgan, happy to do this. I am probably being a bit stupid here, but where exactly can I find the revised test dataset? There is probably some button on this page I cannot find.

**Comment by morganjwilliams** [comment]
I added a [subfolder for 'testing' datasets](https://github.com/morganjwilliams/pyrolite/tree/feature/CIPWNorm/pyrolite/data/testing) on the CIPW Norm branch, as I suspect there might be a few more in the future, you can find it there. I also updated the encoding to UTF8 to solve a few testing headaches - but let me know if this causes issues.

**Comment by ChetanNathwani** [comment]
> I added a [subfolder for 'testing' datasets](https://github.com/morganjwilliams/pyrolite/tree/feature/CIPWNorm/pyrolite/data/testing) on the CIPW Norm branch, as I suspect there might be a few more in the future, you can find it there. I also updated the encoding to UTF8 to solve a few testing headaches - but let me know if this causes issues.

I've run this through SINCLAS, and uploaded the results to my forked pyrolite branch. I don't see any obvious differences between the outputs, nothing for fluorite and magnetite I can see. This makes me think there is definitely a difference with the Fe conversion somewhere...

**Comment by ChetanNathwani** [comment]
> Hey @ChetanNathwani and @bomtuckle, just a quick note that I've merged the feature branch in and created an example on [`develop`](https://pyrolite.readthedocs.io/en/develop/examples/geochem/CIPW.html). For now the Fe-related offsets remain but I've tried to make that clear in the docs and with a warning in the function in the meantime while it eventually gets sorted out.

Nice work!

**Comment by bomtuckle** [comment]
Hi @ChetanNathwani and @morganjwilliams,

Apologies for going quiet for so long. I'm still intending on putting together that paper so I thought I would revisit this issue with the discrepancy in the results.

To simplify the situation, for my testing I converted all of the Fe in the test dataset to Fe2O3T and changed all the rocktypes to 'volcanic' (I assume the igrocs changes the correction based on what is in that column). If you then take the adjusted oxide values from SINCLAS/igrocs and run them through pyrolite (with Fe Adjust set to none), you get very consistent results. So as we have all suspected it must be down to the Fe correction.

I went back to the Verma paper and the only thing I can see vs our code is that Verma says to round to 3dp first, then do the Fe correction. We do it after. Perhaps this is causing some discrepancy to propagate through? I will try and investigate.

The only other thing I have noticed is that there is something funny going on with our olivine, diopside and hypersthene totals. I noticed they were often incorrect compared with the igroc output. However, if you sum up the % of the norm endmembers, the results are much more in line with the igrocs output. Not sure why this happens - suggestions welcome!

Cheers
Tom

**Comment by morganjwilliams** [comment]
Hey @bomtuckle - happy new year! I dug a bit into the `pyrolite.geochem` side of things late last year to check whether there might be a problem deeper there but nothing obvious. The rounding would be a good one to rule out. For the mineral norms - could be something going on in the provisional allocation etc - might be worth having another look through these lines. https://github.com/morganjwilliams/pyrolite/blob/ff907cc8dc85eb5918fd1d9dfa726c057592b275/pyrolite/mineral/normative.py#L806-L909)

**Comment by bomtuckle** [comment]
Hey @morganjwilliams and @ChetanNathwani 

I _think_ I have sorted out all the errors, and the cause isn't what I initially thought.

Turns out the Fe correction was working fine. The issue was actually in the correction of the masses. I couldn't work out what was going wrong with it so went back to my original version of it, which is a bit ugly and verbose, but it works. The results are now spot on.

The other major issue regarding the olivine hypersthene and diopside totals is also sorted. The forsterite formula was incorrectly formatted, and that fixed the olivine issue. I can't actually recall what fixed the hypersthene issue but it seems ok now. As for diopside, there is a discrepancy coming out of the igrocs results. If you sum clinoferrosilite and clinoenstatite it does not equal what it gives for Diopside. So, when we compare our summed outputs to the igrocs diopside there is a difference, but only for some samples. I am starting to think that either igrocs is doing something with the division of diopside that isn't written in the paper, I have misread the paper (though I have gone over it many times) or there is a bug in igrocs.

@morganjwilliams would you be happy to merge my less than optimal code for correcting the masses so that at least the output is working, then we can maybe come up with a more elegant solution in time?

**Comment by morganjwilliams** [comment]
Hey @bomtuckle, nice sleuthing! Not particularly fussed about the formatting, having a reconcilable output is definitely a better outcome. Feel free to open a PR onto `develop` with the substitutions and we can get it merged there; if there's some minor formatting cleanup etc to do I'll look to do so on `develop` before the next release (there's a few bugfixes which need to go out anyway, so with the fixed CIPW, it'll be almost time for v0.3.2).

**Comment by bomtuckle** [comment]
> 

Cheers Morgan. I made my changes on the CIPWnorm branch which had some differences to the most up to date `develop`. I redid my changes on `develop `(which was a little different to my `CIPWnorm`) and in the process of trying to merge the two, something went wrong and it wasn't calculating accurately again. Couldn't for the life of me work out what I had done, so rather than trying to merge the two, I have just replaced everything with the working code.
Anyway, hopefully it all works you merge it back to the main branch.

**Comment by morganjwilliams** [comment]
Hey @bomtuckle! [The outputs look much cleaner now](https://pyrolite.readthedocs.io/en/develop/examples/geochem/CIPW.html#coherency-with-sinclas-igrocs), many thanks! 

I've updated some of the pandas code and some of the hardcoded mass values to make it straightforward to read through, with no obvious differences incurred in the outputs. I think I know where some of the discrepancy came in through the code I'd written earlier, so might be able to reuse that down the track - but for now, it works pretty well.

Let me know if you think of anything else that should be addressed/added to the docs page before the next release; after which I'll look to close this issue.

**Comment by bomtuckle** [comment]
Excellent!

Results are looking good, though a couple of samples are coming out a little different, and I think that's due to IgRoCs using the 'plutonic' le maitre correction rather than volcanic for some samples. Not sure if it's worth editing the test data set to only include the volcanic samples, as otherwise it makes it look like there is a discrepancy when there isn't?

At some point, I think it would be nice to add in the Middlemost Fe correction at some point. I think with the existing TAS functions in Pyrolite it shouldnt be too hard. I might look into that if I have time.

One other trivial (and selfish point), I seem to appear in some lists of contributors but not in the readthedocs contributor's section?

**Comment by morganjwilliams** [comment]
Regarding the last point - sorry for that oversight, should be fixed now! I should add guidelines for PRs which have a note to add your name there, I usually only revisit it before releases etc. 

For the Middlemost Fe correction - if you have time to write up the issue with a reference and any notes around what might be required (unless the time to write the function is less than writing the issue.. which can be the case), I can probably help out in the comment section of that/write up the function.

And for the CIPW test data, we could simply filter it for the docs example and add the note that plutonic samples are being omitted?

**Comment by bomtuckle** [comment]
I did wonder if it was for me to add myself to the list, but I didnt want to presume!

I'll submit a new issue for the Middlemost correction - shouldn't take long.

I think your suggestion to filter for volcanics is good. I think it could be nice to also then filter for plutonic samples so it proves consistency for both corrections.

**Comment by morganjwilliams** [comment]
With v0.3.3 out, CIPW with expanded return options etc are now on main, so this should be stable for now.
