### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by antoine-gs** [morganjwilliams/pyrolite#61]
EDIT: pip maintainers actually discourage installing system wise with sudo pip

(great package by the way!)
When installing system-wise with pip, geochemdb.json is installed as read-only for non-root users (rw-r--r--) which generates an error message when importing the library:
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.9/site-packages/pyrolite/data/geochem/geochemdb.json'

The problem comes from the `with open(path, 'a')` statement in tinydb/storages.py line 31, which requires write permissions.

The issue was fixed by giving users write permission (chmod 666) to geochemdb, but it could be either installed that way or possibly opened as read-only.

**Error message**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/pyrolite/__init__.py", line 13, in <module>
    from .plot import _export_mplstyle
  File "/usr/lib/python3.9/site-packages/pyrolite/plot/__init__.py", line 25, in <module>
    from .. import geochem
  File "/usr/lib/python3.9/site-packages/pyrolite/geochem/__init__.py", line 9, in <module>
    from . import parse
  File "/usr/lib/python3.9/site-packages/pyrolite/geochem/parse.py", line 8, in <module>
    from .ind import (
  File "/usr/lib/python3.9/site-packages/pyrolite/geochem/ind.py", line 530, in <module>
    __db__ = TinyDB(str(pyrolite_datafolder(subfolder="geochem") / "geochemdb.json"))
  File "/usr/lib/python3.9/site-packages/tinydb/database.py", line 94, in __init__
    self._storage = storage(*args, **kwargs)  # type: Storage
  File "/usr/lib/python3.9/site-packages/tinydb/storages.py", line 102, in __init__
    touch(path, create_dirs=create_dirs)
  File "/usr/lib/python3.9/site-packages/tinydb/storages.py", line 31, in touch
    with open(path, 'a'):
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.9/site-packages/pyrolite/data/geochem/geochemdb.json'
```

**To Reproduce**
1.  `sudo pip install pyrolite`
2.  `python 
       \>\>\> import pyrolite`

**Expected behavior**
Readily usable for all users when installed system-wise 

**Environment:**
 - OS: Manjaro Linux 21.1.1
 - Python Version 3.9.6-1
 - Pyrolite Version 0.3.0

**Comment by morganjwilliams** [comment]
Hey @antoine-gs, thanks for the heads up, I'll have a look into this. At this moment I'm not too sure how to manage the permissions for default `pip` installs from my side (other than providing specific documentation around user/system level installation etc), but will do a bit of research to see if I can provide a solution.

**Comment by antoine-gs** [comment]
Yes, I put it here as reference for anyone running into the problem more than anything. Will let you know if I find something too!

**Comment by antoine-gs** [comment]
Turns out that it is officially not recommended to install system-wise with pip, so I would consider the issue closed

**Comment by morganjwilliams** [comment]
Thanks @antoine-gs. I'll modify/add a note in the installation instructions around using `pip install --user`, as this is the better practice for *nix/MacOS systems; for windows perhaps less frequently required.

**Comment by morganjwilliams** [comment]
Confirming that suggestion for the `--user` flag has now been added to the development branch [installation page](https://pyrolite.readthedocs.io/en/develop/installation.html). After the next version there should be a `conda` installation option available which will address some issues here too (#51).
