### ISSUE TITLE
Density plots are inaccurate on ternary diagrams

### ISSUE THREAD

**Issue by morganjwilliams** [morganjwilliams/pyrolite#7]
Using the python-ternary density plot functions, after reimplementing  the ternary heatmap coords function, results in data density mapped to the wrong location.

**Comment by morganjwilliams** [comment]
I've re-implemented how these ternary heatmaps are generated, using pcolormesh or histograms instead of the python-ternary interface.

**Comment by lavender22** [comment]
Out of curiosity, what happens when I reply to these emails?

*Louise Schoneveld*
