### ISSUE TITLE
Remove sphinx dependency

### ISSUE THREAD

**Issue by Elphick** [morganjwilliams/pyrolite#75]
It seems that sphinx has been included as a package dependency.

The dependency list would be reduced if sphinx was added as a dev dependency, minimising the dependency footprint.

**Comment by morganjwilliams** [comment]
Hey @Elphick, thanks for the heads up! I'll take a quick look that I'm not using any of the `sphinx` internals and if not it should indeed be a dev-only dependency.

**Comment by morganjwilliams** [comment]
@Elphick  having a quick look at this one, `sphinx` isn't a direct dependency, but `numpydoc` is, which in turn has a direct dependency on `sphinx`. 

In `pyrolite`, `numpydoc` is used for for parsing and inserting references into a range of docstrings (to e.g. citations and DOIs, and other docstrings). For now I'll leave it as is - but in the future some of these aspects might deserve a bit of a refresh (this resulted in a few warning spam issues in the latest release), and we might be able to drop the `numpydoc` dependency etc.

**Comment by Elphick** [comment]
No worries, thanks for the time to take a look.
