### ISSUE TITLE
Creating additional TAS diagram classification options

### ISSUE THREAD

**Issue by sarahshi** [morganjwilliams/pyrolite#77]
The current TAS diagram option utilizes the Middlemost, 1994 characterization. Additional classifications with the Le Maitre or Le Bas variants of the TAS diagram may provide useful options.

**Comment by morganjwilliams** [comment]
With your PR @ 55e2a09c25db5ad49f58f56928ab553eedf9f4bb, I think we can close this one. This is now on main and was released with v0.3.3. 😄
