### ISSUE TITLE
[BUG] Python 3.9+ tester failure related to matplotlib functions

### ISSUE THREAD

**Issue by bobmyhill** [morganjwilliams/pyrolite#95]
**Describe the bug**
The tester currently fails when building the documentation on python 3.9+
https://github.com/morganjwilliams/pyrolite/actions/runs/6259780432/job/17024364273?pr=92

For more information, search "Error" in the run log.

**Comment by morganjwilliams** [comment]
Well spotted, I think you address this in #96, so will close this once that's merged.
